// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function DeleteNote(arg1:string):Promise<app.WorkspaceData>;

export function EmitMenuAction(arg1:string):Promise<void>;

export function ExportHTML(arg1:app.ExportHTMLRequest):Promise<void>;

export function ExportPDF(arg1:app.ExportPDFRequest):Promise<void>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetDocument(arg1:string):Promise<app.DocumentState>;

export function GetWorkspace():Promise<app.WorkspaceData>;

export function NewDocument():Promise<app.DocumentState>;

export function OpenDocument():Promise<app.WorkspaceData>;

export function OpenDocumentAtPath(arg1:string):Promise<app.WorkspaceData>;

export function RevealNoteInFS(arg1:string):Promise<void>;

export function SaveDocument(arg1:app.SaveDocumentRequest):Promise<app.WorkspaceData>;

export function SaveDocumentAs(arg1:app.SaveDocumentRequest):Promise<app.WorkspaceData>;

export function UpdatePreferences(arg1:app.UpdatePreferencesRequest):Promise<app.AppConfig>;
