// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNote(arg1) {
  return window['go']['app']['App']['DeleteNote'](arg1);
}

export function EmitMenuAction(arg1) {
  return window['go']['app']['App']['EmitMenuAction'](arg1);
}

export function ExportHTML(arg1) {
  return window['go']['app']['App']['ExportHTML'](arg1);
}

export function ExportPDF(arg1) {
  return window['go']['app']['App']['ExportPDF'](arg1);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetDocument(arg1) {
  return window['go']['app']['App']['GetDocument'](arg1);
}

export function GetWorkspace() {
  return window['go']['app']['App']['GetWorkspace']();
}

export function NewDocument() {
  return window['go']['app']['App']['NewDocument']();
}

export function OpenDocument() {
  return window['go']['app']['App']['OpenDocument']();
}

export function OpenDocumentAtPath(arg1) {
  return window['go']['app']['App']['OpenDocumentAtPath'](arg1);
}

export function RevealNoteInFS(arg1) {
  return window['go']['app']['App']['RevealNoteInFS'](arg1);
}

export function SaveDocument(arg1) {
  return window['go']['app']['App']['SaveDocument'](arg1);
}

export function SaveDocumentAs(arg1) {
  return window['go']['app']['App']['SaveDocumentAs'](arg1);
}

export function SaveDraft(arg1, arg2) {
  return window['go']['app']['App']['SaveDraft'](arg1, arg2);
}

export function UpdatePreferences(arg1) {
  return window['go']['app']['App']['UpdatePreferences'](arg1);
}
