export const codeBlockLanguages = [
  {label: 'Plain text', value: ''},
  {label: 'Bash', value: 'bash'},
  {label: 'CSS', value: 'css'},
  {label: 'Go', value: 'go'},
  {label: 'HTML', value: 'html'},
  {label: 'JavaScript', value: 'javascript'},
  {label: 'JSON', value: 'json'},
  {label: 'Markdown', value: 'markdown'},
  {label: 'Python', value: 'python'},
  {label: 'Rust', value: 'rust'},
  {label: 'SQL', value: 'sql'},
  {label: 'TypeScript', value: 'typescript'},
  {label: 'XML', value: 'xml'},
  {label: 'YAML', value: 'yaml'},
];
