// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {document} from '../models';

export function DeleteNote(arg1:string):Promise<document.WorkspaceData>;

export function ExportHTML(arg1:document.ExportHTMLRequest):Promise<void>;

export function ExportPDF(arg1:document.ExportPDFRequest):Promise<void>;

export function ForceQuit():Promise<void>;

export function GetAppInfo():Promise<document.AppInfo>;

export function GetDocument(arg1:string):Promise<document.DocumentState>;

export function GetImagePreview(arg1:string,arg2:string):Promise<string>;

export function GetWorkspace():Promise<document.WorkspaceData>;

export function NewDocument():Promise<document.DocumentState>;

export function OpenDocument():Promise<document.WorkspaceData>;

export function OpenDocumentAtPath(arg1:string):Promise<document.WorkspaceData>;

export function RevealNoteInFS(arg1:string):Promise<void>;

export function SaveDocument(arg1:document.SaveDocumentRequest):Promise<document.WorkspaceData>;

export function SaveDocumentAs(arg1:document.SaveDocumentRequest):Promise<document.WorkspaceData>;

export function SaveDraft(arg1:string,arg2:string):Promise<void>;

export function SelectImage():Promise<string>;

export function UpdatePreferences(arg1:document.UpdatePreferencesRequest):Promise<document.AppConfig>;
