// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function ExportHTML(arg1) {
  return window['go']['main']['App']['ExportHTML'](arg1);
}

export function ExportPDF(arg1) {
  return window['go']['main']['App']['ExportPDF'](arg1);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDocument(arg1) {
  return window['go']['main']['App']['GetDocument'](arg1);
}

export function GetImagePreview(arg1, arg2) {
  return window['go']['main']['App']['GetImagePreview'](arg1, arg2);
}

export function GetWorkspace() {
  return window['go']['main']['App']['GetWorkspace']();
}

export function NewDocument() {
  return window['go']['main']['App']['NewDocument']();
}

export function OpenDocument() {
  return window['go']['main']['App']['OpenDocument']();
}

export function OpenDocumentAtPath(arg1) {
  return window['go']['main']['App']['OpenDocumentAtPath'](arg1);
}

export function RevealNoteInFS(arg1) {
  return window['go']['main']['App']['RevealNoteInFS'](arg1);
}

export function SaveDocument(arg1) {
  return window['go']['main']['App']['SaveDocument'](arg1);
}

export function SaveDocumentAs(arg1) {
  return window['go']['main']['App']['SaveDocumentAs'](arg1);
}

export function SaveDraft(arg1, arg2) {
  return window['go']['main']['App']['SaveDraft'](arg1, arg2);
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}

export function UpdatePreferences(arg1) {
  return window['go']['main']['App']['UpdatePreferences'](arg1);
}
